### ISSUE TITLE
Does not function in FreeNAS

### ISSUE THREAD

**Issue by andrewpurkett** [nicolapcweek94/hak5down#1]
I tried cloning the repo in FreeNAS to run to fill sickbeard, but when I execute the script I get the following error, whether I provide a season, episode, or no parameters:

```
# python hak5down.py              
Traceback (most recent call last):                                              
  File "hak5down.py", line 2, in <module>                                       
    import urllib.request                                                       
ImportError: No module named request                                            
# python hak5down.py -s 9         
Traceback (most recent call last):                                              
  File "hak5down.py", line 2, in <module>                                       
    import urllib.request                                                       
ImportError: No module named request                                            
# python hak5down.py -s 9 -e 1    
Traceback (most recent call last):                                              
  File "hak5down.py", line 2, in <module>                                       
    import urllib.request                                                       
ImportError: No module named request
```

**Comment by nicolapcweek94** [comment]
i'll look into this asap, remember though that this is a python 3 script, i have no idea if freenas aliases python to py3 or if it's still using python 2
run "python" and check what version you're running

**Comment by nicolapcweek94** [comment]
I can confirm that this works on Ubuntu 14.10 on python 3.4.2, try running it with python3 instead of just python.
I have also fixed #2 and it's now saving files as "Hak5 - SxxExx" so that Plex can correctly id them.

**Comment by andrewpurkett** [comment]
@nicolapcweek94 thanks! I should have figured it would require python3, I'll have to add it to a FN jail to run

**Comment by nicolapcweek94** [comment]
no problem, happy someone uses my scripts lol
